# Generated by Django 5.2.8 on 2025-11-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('NACIONAL', 'Parque Nacional da Serra dos Órgãos'), ('ESTADUAL', 'Parque Estadual dos Três Picos'), ('MUNICIPAL', 'Parque Natural Municipal Montanhas de Teresópolis')], max_length=200, unique=True, verbose_name='Nome Oficial do Parque')),
                ('descricao_geral', models.TextField(help_text='Foco em geografia, limites e importância.', verbose_name='Descrição Geral')),
                ('altitude_media', models.IntegerField(blank=True, null=True, verbose_name='Altitude Média (m)')),
                ('horario_funcionamento', models.CharField(max_length=255, verbose_name='Horário de Funcionamento/Temporada')),
            ],
            options={
                'verbose_name': 'Unidade de Conservação',
                'verbose_name_plural': 'Unidades de Conservação',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Evento/Novidade')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Fim (opcional)')),
                ('disponibilidade', models.CharField(help_text="Ex: 'Livre', 'Vagas limitadas', 'Inscrições abertas'.", max_length=255, verbose_name='Detalhes de Disponibilidade/Vagas')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.parque')),
            ],
            options={
                'verbose_name': 'Evento/Novidade',
                'verbose_name_plural': 'Eventos e Novidades',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Trilha')),
                ('descricao', models.TextField(verbose_name='Detalhes da Trilha')),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil'), ('E', 'Extrema')], max_length=1, verbose_name='Nível de Dificuldade')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distância (km)')),
                ('tempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tempo Estimado (h)')),
                ('status_aberta', models.BooleanField(default=True, verbose_name='Trilha Aberta para Visitação')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='api.parque')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'unique_together': {('parque', 'nome')},
            },
        ),
    ]
